### ISSUE TITLE
Arcane Facsimile Macro is non-functional

### ISSUE THREAD

**Issue by CodeMoWerser** [foundryvtt/foundryvtt-premium-content#230]
### What happened?

Occurs in FVTT v10.291, D&D v2.1.4
To replicate: target an actor (any will do) and use the arcane facsimile macro. It will fail with an error.

### What package are you reporting this for?

A House Divided

### Version

1.1.2

### Relevant log output

```shell
Uncaught (in promise) Error: Actor5e [A60ns8tMmTdrXI6U] Model Validation Errors
[Actor5e.items]: Model Validation Errors

Model Validation Errors
[BaseItem.system]: Model Validation Errors
[FeatData.requirements]: may not be undefined
[FeatData.recharge]: may not be undefined
Model Validation Errors
[BaseItem.system]: Model Validation Errors
[FeatData.requirements]: may not be undefined
[FeatData.recharge]: may not be undefined
Model Validation Errors
[BaseItem.system]: Model Validation Errors
[FeatData.requirements]: may not be undefined
[FeatData.recharge]: may not be undefined
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at Actor5e.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseActor (commons.js:7158:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Actor (foundry.js:16292:1)
    at new Actor5e (actor.mjs:10:16)
    at TokenDocument5e.getActor (foundry.js:21987:19)
```

**Comment by CodeMoWerser** [comment]
User (Geekswordsman) provided a fixed macro:
```
{
  "name": "Arcane Facsimile",
  "type": "script",
  "img": "icons/creatures/magical/humanoid-silhouette-glowing-pink.webp",
  "command": "if ( game.user.targets.size != 1) {\n  ui.notifications.warn(\"You must target a single Token\");\n  return;\n}\n\nfunction sleep(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms));\n}\n\n\n// Verify valid target\nconst existingToken = canvas.scene.tokens.get(game.user.targets.ids[0]);\nif ( existingToken._actor.system.details.level >= 10 ) {\n  ui.notifications.warn(\"Target is too high of level (Max: 10)\");\n  return;\n}\nif ( ![ \"sm\", \"med\" ].includes(existingToken._actor.system.traits.size) ) {\n  ui.notifications.warn(\"Target is not the right size (Small or Medium only)\");\n  return;\n}\nif ( !existingToken._actor.system.traits.size in [ \"sm\", \"med\" ] ) {\n  ui.notifications.warn(\"Target is not the right size (Small or Medium only)\");\n  return;\n}\n\n\n// Spawn 3 new cloned Tokens\nconst newToken = foundry.utils.duplicate(existingToken);\nnewToken.hidden = true;\nnewToken.bar1.attribute = null;\nnewToken.actorLink = false;\nconst itemTypesToExclude = [\"class\", \"subclass\", \"spell\", \"feat\"];\nnewToken.actorData = {\n \"name\": \"Reflection of \" + newToken.name,\n \"effects\": [],\n \"items\": existingToken._actor.items.filter(i => !itemTypesToExclude.includes(i.type))\n};\n\n// Append 3 Reflection actions\nlet exampleItem = foundry.utils.mergeObject(foundry.utils.duplicate(newToken.actorData.items[0]), new Item({\"name\": \"Example Item\", \"type\": \"feat\"}));\ndelete exampleItem._id;\nnewToken.actorData.items.push(foundry.utils.mergeObject(exampleItem, {\n  \"img\": \"icons/magic/unholy/orb-stone-pink.webp\",\n  \"type\": \"feat\",\n  \"name\": \"One and Many\",\n  \"system\": {\n    \"description\": { \"value\": \"<p>Whenever the Shard Stalker creates a copy of itself via Shatter Form it is breaking itself into multiple pieces. Each one a reflection of its whole. As long as one reflection or facsimile lives it is considered to be alive.</p><p>There is no distinction between the original, a copy, or a facsimile, they are all the same being, able to act independently while sharing the same thoughts and knowledge.</p>\" }\n  }\n}, { \"inplace\": false }));\nnewToken.actorData.items.push(foundry.utils.mergeObject(exampleItem, {\n  \"img\": \"icons/creatures/magical/humanoid-silhouette-glowing-pink.webp\",\n  \"name\": \"Arcane Facsimile\",\n  \"type\": \"feat\",\n  \"system\": {\n    \"description\": { \"value\": \"<p>When the Shard Stalker uses Shatter Form to make a reflection of itself it can reflect the form of another Small or Medium humanoid it can see with the following traits:</p><ul><li><p>It has all of the ability scores, proficiencies, and other statistics of its target. It also has all of the target creature's equipment and can use it with the same proficiency as the target, though it does not have access to class features, spells, or magical properties of any carried items.</p></li><li><p>Consumable items like food, potions, and scrolls for spells up to 5th level function as expected but can only be used by the Shard Stalker.  Anything taken off of the facsimile instantly shatters into dust as though made of glass or plaster.</p></li></ul><p>The Shard Stalker sounds indistinguishable from the creature they are mirroring, though they can only effectively mimic creatures they've spent at least a full day observing.</p><p>An arcane facsimile can revert itself it its natural form at any time as a bonus action. When an arcane facsimile dies it returns to its true form.</p>\" }\n  }\n}, { \"inplace\": false }));\nnewToken.actorData.items.push(foundry.utils.mergeObject(exampleItem, {\n  \"img\": \"icons/creatures/magical/humanoid-silhouette-dashing-blue.webp\",\n  \"name\": \"Arcane Facsimile - Revert Form\",\n  \"type\": \"feat\",\n  \"system\": {\n    \"description\": { \"value\": \"<p>An arcane facsimile can revert itself it its natural form at any time as a bonus action. When an arcane facsimile dies it returns to its true form.</p><p>@UUID[Macro.LA1NMxqwES2Reb94]{Arcane Facsimile - Revert Form}</p>\" },\n    \"activation\": {\n      \"cost\": 1,\n      \"type\": \"bonus\"\n    }\n  }\n}, { \"inplace\": false }));\n\nconst toCreate = [foundry.utils.duplicate(newToken), foundry.utils.duplicate(newToken), newToken];\ntoCreate[1][\"texture.tint\"] = \"#ff0000\";\ntoCreate[0][\"texture.tint\"] = \"#0000ff\";\nlet created = await canvas.scene.createEmbeddedDocuments(\"Token\", toCreate, {});\n\n// Execute Canvas updates\nnewToken.x += canvas.dimensions.size;\nawait canvas.scene.updateEmbeddedDocuments(\"Token\", [{\"_id\": created[0]._id,  \"x\": newToken.x, \"hidden\": false}], {animation: {duration: 2000}});\nawait sleep(300);\nawait canvas.scene.updateEmbeddedDocuments(\"Token\", [{\"_id\": created[1]._id,  \"x\": newToken.x, \"hidden\": false}], {animation: {duration: 2000}});\nawait sleep(300);\nawait canvas.scene.updateEmbeddedDocuments(\"Token\", [{\"_id\": created[2]._id,  \"x\": newToken.x, \"hidden\": false}], {animation: {duration: 2000}});\nawait sleep(2000);\nawait canvas.scene.updateEmbeddedDocuments(\"Token\", [{\"_id\": created[2]._id,  \"bar1.attribute\": \"attributes.hp\"}], {animation: {duration: 2000}});\nawait canvas.scene.deleteEmbeddedDocuments(\"Token\", [created[0]._id, created[1]._id], {});",
  "author": "PFxs2BLBwX4c4U95",
  "scope": "global",
  "flags": {
    "exportSource": {
      "world": "a-house-divided",
      "system": "dnd5e",
      "coreVersion": "10.291",
      "systemVersion": "2.1.4"
    }
  },
  "_stats": {
    "systemId": "dnd5e",
    "systemVersion": "2.1.4",
    "coreVersion": "10.291",
    "createdTime": 1665156917453,
    "modifiedTime": 1675456128775,
    "lastModifiedBy": "PFxs2BLBwX4c4U95"
  }
}
```
