### ISSUE TITLE
[Bug]: undefined (reading '0') after while abomination vault is attempting to import

### ISSUE THREAD

**Issue by atroposfate** [foundryvtt/foundryvtt-premium-content#330]
### What happened?

I was using version 10 and was working fine then just upgraded to 11.308 and updated all the modules. I created a new world and activate the abomination vault module and click import but it gets to 44% and produces the error attached. I've tried it 5 or 6 times some without any additional modules added and with this as the only module and still get the same result.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.0

### Relevant log output

```shell
FoundryVTT | 2023-09-01 16:09:57 | [error] Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at Tokenizer.stateBeforeEntity (/home/ry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:584:47)
    at Tokenizer.parse (/home/ry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:848:26)
    at Tokenizer.write (/home/ry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:159:14)
    at Parser.write (/home/ry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Parser.js:459:28)
    at sanitizeHtml (/home/ry/foundryvtt/resources/app/node_modules/sanitize-html/index.js:588:10)
    at cleanHTML (file:///home/ry/foundryvtt/resources/app/dist/database/validators.mjs:1:233)
    at HTMLField.sanitizeHTMLField [as sanitize] (file:///home/ry/foundryvtt/resources/app/dist/database/sanitization.mjs:1:1235)
    at Item._sanitizeFields (file:///home/ry/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7638)
    at Item._sanitizeFields (file:///home/ry/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7865)
    at Item._sanitizeFields (file:///home/ry/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7865)
```

**Comment by atroposfate** [comment]
Did a uninstall and reinstall and it works now
