### ISSUE TITLE
[Bug]: Can't import Kingmaker adventure

### ISSUE THREAD

**Issue by bfabe8** [foundryvtt/foundryvtt-premium-content#345]
### What happened?

When attempting to import the Kingmaker Adventure, I get the following error:
`Cannot read properties of undefined (reading '0')`

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.01

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading '0')\n    at Tokenizer.stateBeforeEntity (C:\\Program Files\\FoundryVTT\\resources\\app\\node_modules\\htmlparser2\\lib\\Tokenizer.js:584:47)\n    at Tokenizer.parse (C:\\Program Files\\FoundryVTT\\resources\\app\\node_modules\\htmlparser2\\lib\\Tokenizer.js:848:26)\n    at Tokenizer.write (C:\\Program Files\\FoundryVTT\\resources\\app\\node_modules\\htmlparser2\\lib\\Tokenizer.js:159:14)\n    at Parser.write (C:\\Program Files\\FoundryVTT\\resources\\app\\node_modules\\htmlparser2\\lib\\Parser.js:459:28)\n    at sanitizeHtml (C:\\Program Files\\FoundryVTT\\resources\\app\\node_modules\\sanitize-html\\index.js:588:10)\n    at cleanHTML (file:///C:/Program%20Files/FoundryVTT/resources/app/dist/database/validators.mjs:1:233)\n    at HTMLField.sanitizeHTMLField [as sanitize] (file:///C:/Program%20Files/FoundryVTT/resources/app/dist/database/sanitization.mjs:1:1235)\n    at Function._sanitizeFields (file:///C:/Program%20Files/FoundryVTT/resources/app/dist/database/backend/server-document.mjs:1:7729)\n    at Function._sanitizeFields (file:///C:/Program%20Files/FoundryVTT/resources/app/dist/database/backend/server-document.mjs:1:7956)\n    at Function._sanitizeFields (file:///C:/Program%20Files/FoundryVTT/resources/app/dist/database/backend/server-document.mjs:1:7956)
```

**Comment by bfabe8** [comment]
It seems that reinstalling Foundry fixed the issue
