### ISSUE TITLE
[Bug]: Adventure Import hangs at 27%

### ISSUE THREAD

**Issue by FredisMyEvilTwin** [foundryvtt/foundryvtt-premium-content#485]
### What happened?

When attempting to import the adventure on a fresh world (no other modules installed), the installation hangs at 27%. The issue happens each time I attempt to install on a new world, if I stop the process and restart the installation hangs at 1%. I have attached a screenshot of the console output. I am running Foundry via Ubuntu server  using a linux-based Docker container. 

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/158524501/cfa9bcb0-fc3d-4384-ad0a-bec522f1a995)

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.0.0

### Relevant log output

```shell
Cannot read properties of undefined (reading 'length')
fetch @ foundry.js:68326
foundry.js:6629 TypeError: Cannot read properties of undefined (reading 'length')
    at Preprocessor.advance (/home/foundry/resources/app/node_modules/parse5/dist/tokenizer/preprocessor.js:138:35)
    at Tokenizer._consume (/home/foundry/resources/app/node_modules/parse5/dist/tokenizer/index.js:270:34)
    at Tokenizer._runParsingLoop (/home/foundry/resources/app/node_modules/parse5/dist/tokenizer/index.js:221:29)
    at Tokenizer.write (/home/foundry/resources/app/node_modules/parse5/dist/tokenizer/index.js:248:14)
    at parseFragment (/home/foundry/resources/app/node_modules/parse5/dist/index.js:42:22)
    at cleanHTML (/home/foundry/resources/app/dist/database/validators.mjs:1:209)
    at HTMLField.sanitizeHTMLField [as sanitize] (/home/foundry/resources/app/dist/database/sanitization.mjs:1:1235)
    at Item._sanitizeFields (/home/foundry/resources/app/dist/database/backend/server-document.mjs:1:7729)
    at Item._sanitizeFields (/home/foundry/resources/app/dist/database/backend/server-document.mjs:1:7956)
    at Item.sanitizeUserInput (/home/foundry/resources/app/dist/database/backend/server-document.mjs:1:7436)
_onSubmit @ foundry.js:6629
game:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

**Comment by FredisMyEvilTwin** [comment]
looks like it was an old Node version. pulled an update and everything installed correctly. I was/am on 315.

**Comment by aaclayton** [comment]
Thanks for confirming, closing!
