### ISSUE TITLE
[Bug]: PF2e Abomination Vaults - Warning Messages on Adventure Import

### ISSUE THREAD

**Issue by ottyn** [foundryvtt/foundryvtt-premium-content#551]
### What happened?

Foundry 11.315
PF2e System 5.15.3

Fresh world, no modules active except for the Abomination Vaults module.

On performing the initial import of the AV module, the following Warnings are posted to the console.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.1

### Relevant log output

```shell
commons.js:2070 Error: The undefined class overrides the AdventureImporter#_prepareImportData or 
      AdventureImporter#_importContent methods. As such a legacy import workflow will be used, but this workflow is 
      deprecated. Your importer should now call the new Adventure#import, Adventure#prepareImport, 
      or Adventure#importContent methods.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at PF2EAdventureImporter._updateObject (foundry.js:71966:21)
    at PF2EAdventureImporter._onSubmit (foundry.js:6626:18)
logCompatibilityWarning @ commons.js:2070
commons.js:2070 Error: AdventureImporter#_prepareImportData is deprecated. Please use Adventure#prepareImport instead.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at PF2EAdventureImporter._prepareImportData (foundry.js:72021:19)
    at PF2EAdventureImporter._prepareImportData (importer.mjs:129:61)
    at PF2EAdventureImporter._importLegacy (foundry.js:71984:60)
    at PF2EAdventureImporter._updateObject (foundry.js:71967:19)
    at PF2EAdventureImporter._onSubmit (foundry.js:6626:18)
logCompatibilityWarning @ commons.js:2070
importer.mjs:198 [pf2e-abomination-vaults] Actor "Belcorra's Desk" [sAPpmNqvn6SxYS2y] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Kobold Bones" [K5x037uBxKtreY4v] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Shrine Compartment" [FN5c95GBzHWDbXbP] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Thief's Remains" [VJ8t4Uo2LSiRSuFz] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Borbo's Stash" [BhcCzIMpz9wD2PWh] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Drake's Sea Chest" [S8VDmNHzkFEmjWfL] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Mimnivix's Treasure" [WgqdPlzcS4OMewi7] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Osprey Thieves' Gear" [abNUVCJeb4uXcbS3] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Shrine Offerings" [Kc0uVS1nGVUJLIU8] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Guard Cache" [ArSUed6YY9DhoIrX] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:215 [pf2e-abomination-vaults] Compendium source data for "Jarelle's Remains" [7X6SlSnDyVvpCdSc] not found in pack 7X6SlSnDyVvpCdSc.undefined.
#mergeCompendiumActors @ importer.mjs:215
importer.mjs:198 [pf2e-abomination-vaults] Actor "Repair Materials" [eVJazBubc7PIlaWc] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Scriptorium Books" [OTk9VX3iqpLGx8s0] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Secure Collection" [SVU5QArj8vuvPicl] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Guests' Remains" [e2P51BCKzDposq6L] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Lounge Desk" [S75QQzSaqjyjOc2f] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Otari's Equipment" [EwEHsQB88dUbcmeE] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Trophy Vault" [uQ6VezqcETteigVY] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Medical Supplies" [dn2nyTu7rTQxte8J] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Siora's Footlocker" [ZlB1WFKgyDUr6CPg] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Supply Room Shelves" [aOGmhGueWJkssO3h] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Throne Compartment" [03vuZCya3T9tnqCG] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:215 [pf2e-abomination-vaults] Compendium source data for "Dissection Chamber Detritus" [SdhFlXxykBCiK3SU] not found in pack SdhFlXxykBCiK3SU.undefined.
#mergeCompendiumActors @ importer.mjs:215
importer.mjs:198 [pf2e-abomination-vaults] Actor "Jafaki's Laboratory" [Qpxj7x2ZppXLzaPl] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Murschen's Treasures" [Wc5dPvLQDUit2wwq] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Weapon Racks" [IwAwqnXkU8t4U2hp] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Grim Offerings" [AQh6XKPQLhxw4DVS] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Hellforge Materials" [TXnAx3WaWHSn8nBy] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Infernal Armory" [nwef3ap1ATjGYdvx] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Bodak Treasure" [dczBOCUfY2fXGzf4] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Chuul Nest" [mEfaPB3TTjkUD16h] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Drow Provisions" [QGrSDTxJDTVubTPY] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Gemstone-studded Skull" [CJJqBzrqruRCufeB] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Hanging Treasure" [6OrsuoAvyTpqqtxe] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Iron Strongbox" [4oiB7prL9wIerPY8] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Secret Treasury" [pxuKJ9IqbeBPYjN2] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Coin Vault" [G5qIaqPrLKK0gwz4] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Derelict Armory" [3R2NgS7KzooSqidC] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Old Rowboat" [JLD4vuTKjfWvoOff] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Quara's Chest" [841KHr3QCEg8IdNn] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Ravirex's Hoard" [sgQCxACQTgxm8C1N] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Urdefhan Tribute" [d7Os57bGrdmJDPzT] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Vault of Secrets" [xEJHglwTvuHoI9vG] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:198 [pf2e-abomination-vaults] Actor "Webbing" [eomAmy6pj0uYoMS1] had no sourceId to retrieve source data from.
#mergeCompendiumActors @ importer.mjs:198
importer.mjs:215 [pf2e-abomination-vaults] Compendium source data for "Chandriu's Remains" [6dYeLCCdOogucfQs] not found in pack 6dYeLCCdOogucfQs.undefined.
#mergeCompendiumActors @ importer.mjs:215
commons.js:2070 Error: AdventureImporter#_importContent is deprecated. Please use Adventure#importContent instead.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at PF2EAdventureImporter._importContent (foundry.js:72033:19)
    at PF2EAdventureImporter._importContent (importer.mjs:155:38)
    at PF2EAdventureImporter._importLegacy (foundry.js:72003:43)
    at async PF2EAdventureImporter._onSubmit (foundry.js:6626:7)
logCompatibilityWarning @ commons.js:2070
```

**Comment by silvative** [comment]
I believe the deprecation warnings are the same ones mentioned in #554 , so I'll link this there just to make sure it's checked over at the same time. 
The log messages about loot actors lacking sourceID are expected as they are provided by the module and not the system, so there's nothing to be concerned about there!
