### ISSUE TITLE
[Bug]: "Advance Sundial of Aten" macro no longer works in v12

### ISSUE THREAD

**Issue by Daeke** [foundryvtt/foundryvtt-premium-content#571]
### What happened?

The existing macro looks like this:
`const dial = canvas.scene.lights.get("ozpgBI74DdbovJIM");`
`dial.update({rotation: dial.data.rotation + 5});`
`game.time.advance(1200);`

When clicked, the console error below is thrown.

I believe this just needs to have `dial.data.rotation` changed to `dial.rotation` and it should work?

### What package are you reporting this for?

The Demon Queen Awakens

### Version

4.0.0

### Relevant log output

```shell
VM2811:4 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'rotation')
    at Macro.eval (eval at #executeScript (foundry.js:19863:16), <anonymous>:4:34)
    at #executeScript (foundry.js:19868:17)
    at Macro.execute (foundry.js:19815:35)
    at Hotbar._onClickMacro (foundry.js:81883:20)
    at HTMLLIElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
```

**Comment by anathemamask** [comment]
I verified this was functioning just yesterday, so I suspect that this issue results from not reimporting the adventure in v12. Can you do so and let me know if it works after that? :)

**Comment by BPtacek** [comment]
Sadly, not working. New world, V12 + Pathfinder 2e v6 beta 3

**Comment by Daeke** [comment]
Yes, I verified this originally on a brand new Foundry install with a new world and import. I haven’t checked on the latest PF beta but I see the user above me has.

**Comment by Daeke** [comment]
Reverified on a fresh install:
Foundry 12.327
PF2e v6.0.0-beta3
Demon Queen v4.0.1
