### ISSUE TITLE
Pathfinder 2E - Beginner Box issue

### ISSUE THREAD

**Issue by Ixitak** [foundryvtt/foundryvtt-premium-content#573]
### What happened?

I tried to install the beginner box moduls in foundry but i couldn't import the adventure in german. 
A clean install in english works. 

The Version numbers i use: 
foundry 11.315
Pathfinder 2e 5.16.1
Pathfinder Beginner Box 4.0.1

The recommanded moduls for language:
babele v2.5.4
German [Pathfinder 2e] v5.16.0.0
libwrapper v1.12.13.1

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

4.0.1

### Relevant log output

```shell
undry.js:6629 Error: ItemPF2e [Him8OezIZfA7czXh] validation errors:
  type: may not be undefined
    at DataModelValidationFailure.asError (commons.js:3894:14)
    at ItemPF2e.validate (commons.js:7164:61)
    at new DataModel (commons.js:6918:12)
    at new ClientDocumentMixin (foundry.js:13979:7)
    at new ItemPF2e (pf2e.mjs:1621:323477)
    at Object.construct (pf2e.mjs:1621:341050)
    at EmbeddedCollection.createDocument (commons.js:4412:14)
    at EmbeddedCollection._createOrUpdate (commons.js:4597:26)
    at EmbeddedCollection.update (commons.js:4573:14)
    at #updateField (commons.js:7326:33)
    at #updateData (commons.js:7302:26)
    at LootPF2e.updateSource (commons.js:7258:30)
    at #applyTranslations (importer.mjs:226:13)
    at PF2EAdventureImporter._prepareImportData (importer.mjs:83:34)
    at async PF2EAdventureImporter._importLegacy (foundry.js:71984:49)
    at async PF2EAdventureImporter._onSubmit (foundry.js:6626:7)
_onSubmit @ foundry.js:6629
```

**Comment by silvative** [comment]
Hi, I'm sorry for the issue you were encountering. I believe this has been fixed as of version 4.0.2, but please let me know if that isn't the case, and I can pass it on to localisation team.
