### ISSUE TITLE
[Bug]: Abomination Vaults fails to update world description

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt-premium-content#588]
### What happened?

Abomination Vaults installer is trying to call `game.world.data.update` rather than `game.world.update`

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.3

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'update')
    at Object.handler (adventure.mjs:84:25)
    at async PF2EAdventureImporter._importContent (importer.mjs:162:7)
    at async PF2EAdventureImporter._importLegacy (foundry.js:75014:32)
    at async PF2EAdventureImporter._onSubmit (foundry.js:6641:7)
```

**Comment by silvative** [comment]
Good catch- and thank you for the extra detailed report, it made this especially easy to resolve !
