### ISSUE TITLE
[Bug]: Tattoo's not working

### ISSUE THREAD

**Issue by robgrahamau** [foundryvtt/foundryvtt-premium-content#606]
### What happened?

Since the last update of Tasha's cauldron I am getting an error on anything that has a tattoo on it and any time I create a tattoo, the sheet for the tattoo will not open either the error is shown here 

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/28775608/5c9e1bb6-e3a7-443b-b825-b3b289eb2884)

### What package are you reporting this for?

Tasha's Cauldron of Everything

### Version

1.1.0

### Relevant log output

```shell
Error: An error occurred while rendering TattooSheet 92. Cannot read properties of undefined (reading 'activation')
    at Hooks.onError (foundry.js:630:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5771:13Caused by: TypeError: Cannot read properties of undefined (reading 'activation')
    at TattooSheet._getItemProperties (item-sheet.mjs:427:25)
    at TattooSheet.getData (item-sheet.mjs:111:28)
    at async TattooSheet.getData (tattoo-sheet.mjs:20:21)
    at async TattooSheet._render (foundry.js:5814:18)
    at async TattooSheet._render (foundry.js:6548:5)
    at async TattooSheet._render (foundry.js:7134:5)
```

**Comment by robgrahamau** [comment]
Have confirmed too that a raw new world with just tasha'a and the DND5E installation causes it
```error: An error occurred while rendering TattooSheet 40. Cannot read properties of undefined (reading 'activation')
    at Hooks.onError (foundry.js:630:24)
    at foundry.js:5771:13Caused by: TypeError: Cannot read properties of undefined (reading 'activation')
    at TattooSheet._getItemProperties (item-sheet.mjs:427:25)
    at TattooSheet.getData (item-sheet.mjs:111:28)
    at async TattooSheet.getData (tattoo-sheet.mjs:20:21)
    at async TattooSheet._render (foundry.js:5814:18)
    at async TattooSheet._render (foundry.js:6548:5)
    at async TattooSheet._render (foundry.js:7134:5)
    ```
