### ISSUE TITLE
[Bug]:  Pathfinder: Kingmaker:  Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by hmmthinking** [foundryvtt/foundryvtt-premium-content#620]
### What happened?

Node version: 20.15.1
Foundry Version: 12 Build 329
Pathfinder Version: 6.1.0

I am attempting to install the adventure for Pathfinder: Kingmaker from its compendium pack, but each time I try to install it I get the attached output in the logs. I have disabled all other modules, but regardless of the modules I have enabled it always shows this output. This is a completely empty game with no characters, journal entries, encounters, or scenes. This is occurring in all browsers. Troubleshooting steps I've attempted:

1. Reinstalling the Pathfinder: Kingmaker Add-On Module.
2. Reinstalling the Pathfinder Second Edition Game System.
3. Updating All Add-On Modules.
4. Updating Foundry to the latest stable version.
5. Creating a new world.

I am using Foundry's CLI version because I will eventually be hosting the game for other players. Please let me know if any other information is needed.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.1.1

### Relevant log output

```shell
FoundryVTT | 2024-07-21 15:18:50 | [error] Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at Tokenizer.stateBeforeEntity (C:\Users\Administrator\Documents\Foundry\foundryvtt\resources\app\node_modules\htmlparser2\lib\Tokenizer.js:584:47)
    at Tokenizer.parse (C:\Users\Administrator\Documents\Foundry\foundryvtt\resources\app\node_modules\htmlparser2\lib\Tokenizer.js:848:26)
    at Tokenizer.write (C:\Users\Administrator\Documents\Foundry\foundryvtt\resources\app\node_modules\htmlparser2\lib\Tokenizer.js:159:14)
    at Parser.write (C:\Users\Administrator\Documents\Foundry\foundryvtt\resources\app\node_modules\htmlparser2\lib\Parser.js:459:28)
    at sanitizeHtml (C:\Users\Administrator\Documents\Foundry\foundryvtt\resources\app\node_modules\sanitize-html\index.js:606:10)
    at cleanHTML (file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/dist/database/validators.mjs:1:233)
    at HTMLField.sanitizeHTMLField [as sanitize] (file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/dist/database/sanitization.mjs:1:1461)
    at #i (file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:12224)
    at #i (file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:12394)
    at #i (file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:12394)
    at Actor.sanitizeUserInput (file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:11785)
    at Actor.preprocessData (file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:15353)
    at file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:3276
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._createDocuments (file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:3073)
    at ServerDatabaseBackend.create (file:///C:/Users/Administrator/Documents/Foundry/foundryvtt/resources/app/common/abstract/backend.mjs:77:17)
```

**Comment by hmmthinking** [comment]
Fixed with clean Foundry install instead of updating from inside the app.
