### ISSUE TITLE
[Bug]: Failed data preparation for Compendium.dnd-phandelver-below.pbso-adventures.Adventure.p9BGA2AmnAZJCwow.Actor.pQjF6emUcfloErNr.Item.y2gedSvOCzRCxLFf. Cannot read properties of null (reading 'items')

### ISSUE THREAD

**Issue by PhDaveMil** [foundryvtt/foundryvtt-premium-content#885]
### What happened?

Ever since the new update, Phandelver is creating lots of errors in the Console. We are talking over a thousand errors. I am not sure what these errors are actually doing, but this is a screen capture of what the console looks like:

![image](https://github.com/user-attachments/assets/99edb8c7-5801-4281-80e7-5c796f52276d)

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.2.1

### Relevant log output

```shell
foundry.js:655 Error: Failed data preparation for Compendium.dnd-phandelver-below.pbso-adventures.Adventure.p9BGA2AmnAZJCwow.Actor.pQjF6emUcfloErNr.Item.y2gedSvOCzRCxLFf. Cannot read properties of null (reading 'items')
    at Hooks.onError (foundry.js:654:24)
    at Item5e._safePrepareData (foundry.js:10801:15)
    at Item5e._initialize (foundry.js:10630:19)
    at new DataModel (foundry-esm.js:10182:12)
    at new Document (foundry-esm.js:10955:3)
    at new BaseItem (foundry-esm.js:14686:7)
    at new ClientDocumentMixin (foundry.js:10594:7)
    at new Item5e (item.mjs:21:16)
    at EmbeddedCollection.createDocument (foundry-esm.js:5230:14)
    at EmbeddedCollection._initializeDocument (foundry-esm.js:5270:20)
Caused by: TypeError: Cannot read properties of null (reading 'items')
    at SpellData.prepareBaseData (abstract.mjs:470:54)
    at Item5e.prepareData (foundry.js:10820:37)
    at Item5e.prepareData (flags.mjs:21:11)
    at Item5e._safePrepareData (foundry.js:10799:14)
    at Item5e._initialize (foundry.js:10630:19)
    at new DataModel (foundry-esm.js:10182:12)
    at new Document (foundry-esm.js:10955:3)
    at new BaseItem (foundry-esm.js:14686:7)
    at new ClientDocumentMixin (foundry.js:10594:7)
    at new Item5e (item.mjs:21:16)
onError	@	foundry.js:655
_safePrepareData	@	foundry.js:10801
_initialize	@	foundry.js:10630
DataModel	@	foundry-esm.js:10182
Document	@	foundry-esm.js:10955
BaseItem	@	foundry-esm.js:14686
ClientDocumentMixin	@	foundry.js:10594
Item5e	@	item.mjs:21
createDocument	@	foundry-esm.js:5230
_initializeDocument	@	foundry-esm.js:5270
initialize	@	foundry-esm.js:5254
initialize	@	foundry-esm.js:8872
_initialize	@	foundry-esm.js:10340
_initialize	@	foundry-esm.js:11020
DataModel	@	foundry-esm.js:10182
Document	@	foundry-esm.js:10955
BaseActor	@	foundry-esm.js:13233
initialize	@	foundry-esm.js:8768
(anonymous)	@	foundry-esm.js:8568
initialize	@	foundry-esm.js:8568
initialize	@	foundry-esm.js:8678
_initialize	@	foundry-esm.js:10340
_initialize	@	foundry-esm.js:11020
_initialize	@	foundry.js:10628
DataModel	@	foundry-esm.js:10182
Document	@	foundry-esm.js:10955
BaseAdventure	@	foundry-esm.js:13586
ClientDocumentMixin	@	foundry.js:10594
Adventure	@	foundry.js:16189
fromSource	@	foundry-esm.js:10657
fromSource	@	foundry.js:16200
(anonymous)	@	foundry-esm.js:56334
_getDocuments	@	foundry-esm.js:56334
await in _getDocuments		
get	@	foundry-esm.js:12237
await in get		
getDocuments	@	foundry.js:13145
getDocument	@	foundry.js:13117
(anonymous)	@	dnd-phandelver-below.mjs:51
#call	@	foundry.js:632
callAll	@	foundry.js:589
setupGame	@	foundry.js:9098
```

**Comment by krbz999** [comment]
This looks like https://github.com/foundryvtt/dnd5e/issues/4837 which was fixed a while back.
