### ISSUE TITLE
[Bug]: Adding a settlement to the Kingdom sheet seems to breaks it

### ISSUE THREAD

**Issue by brettwon** [foundryvtt/foundryvtt-premium-content#898]
### What happened?

When clicking the Add button under the Kingdom sheet, World, Kingdom Settlements, it freezes the rest of the sheet without adding anything. I can still close the sheet, but it cannot be reopened. Upon a refresh, it can be opened and can then edit new settlements, but it would be nice to not have to refresh Foundry to add a new settlement i guess. 

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.1.1

### Relevant log output

```shell
Error: Failed data preparation for Actor.xxxPF2ExPARTYxxx. Cannot read properties of undefined (reading 'consumption')
    at Hooks.onError (foundry.js:654:24)
    at PartyPF2e._safePrepareData (foundry.js:10801:15)
    at PartyPF2e._initialize (foundry.js:10630:19)
    at PartyPF2e._initialize (pf2e.mjs:1608:57066)
    at PartyPF2e.updateSource (foundry-esm.js:10520:35)
    at PartyPF2e.updateSource (pf2e.mjs:1608:249035)
    at #handleUpdateDocuments (foundry-esm.js:56579:13)
    at async PartyPF2e.updateDocuments (foundry-esm.js:11473:23)
    at async PartyPF2e.update (foundry-esm.js:11584:23)
    at async Kingdom.update (pf2e.mjs:1608:220875)


Error: An error occurred while rendering KingdomSheetPF2e 32. Cannot read properties of undefined (reading 'level')
    at Hooks.onError (foundry.js:654:24)
    at foundry.js:5795:13
```

**Comment by tnarv** [comment]
Also having this issue. PF2e v6.8.1/Foundry v12.333

Thought maybe it was a Forge issue but the issue persists even on a local instance.

**Comment by silvative** [comment]
Hi, I believe this issue has been fixed by a system update but please let me know if that is not the case!
